fix(test): js test fails due to missing jest-cli module
Without explicit dependency javascript test fails with the following
error:

stderr: Error: Cannot find module 'jest-cli/bin/jest'